import React, { createContext, useContext, useMemo } from 'react';
import useSettingsStore from '../store/settingsStore';
import * as LucideIcons from 'lucide-react';

const semanticMap = {
  folder: { lucide: 'Folder' },
  file: { lucide: 'File' },
  chat: { lucide: 'MessageSquare' },
  search: { lucide: 'Search' },
  settings: { lucide: 'Settings' },
  mic: { lucide: 'Mic' },
  speaker: { lucide: 'Volume2' },
  download: { lucide: 'Download' },
  x: { lucide: 'X' },
  mail: { lucide: 'Mail' },
  trash: { lucide: 'Trash2' },
  plus: { lucide: 'Plus' },
  edit: { lucide: 'Pencil' },
  x: { lucide: 'X' },
  'rotate-ccw': { lucide: 'RotateCcw' },
  'download': { lucide: 'Download' },
  check: { lucide: 'Check' },
  'chevron-right': { lucide: 'ChevronRight' },
  'chevron-down': { lucide: 'ChevronDown' },
  'more-vertical': { lucide: 'MoreVertical' },
  upload: { lucide: 'Upload' },
  'file-text': { lucide: 'FileText' },
  receipt: { lucide: 'Receipt' },
  'file-image': { lucide: 'FileImage' },
  image: { lucide: 'Image' },
  palette: { lucide: 'Palette' },
  send: { lucide: 'Send' },
  home: { lucide: 'Home' },
  'stop-circle': { lucide: 'StopCircle' },
  loader: { lucide: 'Loader2' },
  'alert-circle': { lucide: 'AlertCircle' },
  copy: { lucide: 'Copy' },
  'external-link': { lucide: 'ExternalLink' },
  'log-out': { lucide: 'LogOut' },
  sparkles: { lucide: 'Sparkles' },
  'file-down': { lucide: 'FileDown' },
  'file-up': { lucide: 'FileUp' },
  cloud: { lucide: 'Cloud' },
  'alert-triangle': { lucide: 'AlertTriangle' },
  compress: { lucide: 'Minimize2' },
  globe: { lucide: 'Globe' },
  productScout: { lucide: 'ShoppingCart' },
  'shield-check': { lucide: 'ShieldCheck' },
  radar: { lucide: 'Radar' },
  'trending-up': { lucide: 'TrendingUp' },
  'eye': { lucide: 'Eye' },
  'scan-search': { lucide: 'ScanSearch' },
  megaphone: { lucide: 'Megaphone' },
  link: { lucide: 'Link' },
  star: { lucide: 'Star' },
  'star-off': { lucide: 'StarOff' },
  book: { lucide: 'BookOpen' },
  brain: { lucide: 'Brain' },
  keyboard: { lucide: 'Keyboard' },
  flame: { lucide: 'Flame' },
  coins: { lucide: 'Coins' },
  'git-branch': { lucide: 'GitBranch' },
  'refresh-cw': { lucide: 'RefreshCw' },
  user: { lucide: 'User' },
  pin: { lucide: 'Pin' },
  'folder-open': { lucide: 'FolderOpen' },
  'folder-plus': { lucide: 'FolderPlus' },
  cpu: { lucide: 'Cpu' },
  files: { lucide: 'Files' },
  compare: { lucide: 'GitCompare' },
  debate: { lucide: 'Swords' },
  eye: { lucide: 'Eye' },
  'eye-off': { lucide: 'EyeOff' },
  'bar-chart': { lucide: 'BarChart2' },
  'clock': { lucide: 'Clock' },
  'history': { lucide: 'History' },
  'message-circle': { lucide: 'MessageCircle' },
  'list-checks': { lucide: 'ListChecks' },
  'check-circle': { lucide: 'CheckCircle2' },
  'circle': { lucide: 'Circle' },
  'calendar': { lucide: 'Calendar' },
  'tag': { lucide: 'Tag' },
  'wand': { lucide: 'Wand2' },
  'grip-vertical': { lucide: 'GripVertical' },
  'layout': { lucide: 'LayoutDashboard' },
  'columns': { lucide: 'Columns2' },
  'expand-horizontal': { lucide: 'ChevronsLeftRight' },
  'collapse-horizontal': { lucide: 'ChevronsRightLeft' },
  'share-2': { lucide: 'Share2' },
  'calendar-check': { lucide: 'CalendarCheck' },
  'arrow-right': { lucide: 'ArrowRight' },
  'arrow-left': { lucide: 'ArrowLeft' },
  key: { lucide: 'Key' },
  calculator: { lucide: 'Calculator' },
  'check-square': { lucide: 'CheckSquare' },
  'target': { lucide: 'Target' },
  'compass': { lucide: 'Compass' },
  'pen-line': { lucide: 'PenLine' },
  'archive': { lucide: 'Archive' },
  'chevron-left': { lucide: 'ChevronLeft' },
  'lightbulb':    { lucide: 'Lightbulb' },
  'crosshair':    { lucide: 'Crosshair' },
  'briefcase':    { lucide: 'Briefcase' },
  'menu':           { lucide: 'Menu' },
  'smartphone':     { lucide: 'Smartphone' },
  'more-horizontal': { lucide: 'MoreHorizontal' },
  'help-circle':    { lucide: 'HelpCircle' },
  'brush':          { lucide: 'Brush' },
  'scan-search':    { lucide: 'ScanSearch' },
  gauge: { lucide: 'Gauge' },
  'line-chart': { lucide: 'LineChart' },
  'graduation-cap': { lucide: 'GraduationCap' },
  'clipboard-list': { lucide: 'ClipboardList' },
  'heart-pulse': { lucide: 'HeartPulse' },
  'layers': { lucide: 'Layers' },
  blocks: { lucide: 'Blocks' },
  square: { lucide: 'Square' },
  library: { lucide: 'Library' },
  inbox: { lucide: 'Inbox' },
  scissors: { lucide: 'Scissors' },
  crop: { lucide: 'Crop' },
  shield: { lucide: 'Shield' },
  grid: { lucide: 'LayoutGrid' },
  droplets: { lucide: 'Droplets' },
  sliders: { lucide: 'SlidersHorizontal' },
  type: { lucide: 'Type' },
  swatch: { lucide: 'SwatchBook' },
  frame: { lucide: 'Frame' },
  'app-window': { lucide: 'AppWindow' },
  shapes: { lucide: 'Shapes' },
  'layout-grid': { lucide: 'LayoutGrid' },
  info: { lucide: 'Info' },
  'file-stack': { lucide: 'FileStack' },
  printer: { lucide: 'Printer' },
  'bar-chart': { lucide: 'BarChart3' },
  contrast: { lucide: 'Contrast' },
  film: { lucide: 'Film' },
  utensils: { lucide: 'UtensilsCrossed' },
  'shopping-cart': { lucide: 'ShoppingCart' },
  link: { lucide: 'Link' },
  'file-text': { lucide: 'FileText' },
  workflow: { lucide: 'Workflow' },
  eraser: { lucide: 'Eraser' },
  zap: { lucide: 'Zap' },
  focus: { lucide: 'Focus' },
  trapezoid: { lucide: 'Scaling' },
  aim: { lucide: 'Crosshair' },
  'palette-2': { lucide: 'PaintBucket' },
  text: { lucide: 'Type' },
  combine: { lucide: 'Combine' },
  'rotate-cw': { lucide: 'RotateCw' },
  hash: { lucide: 'Hash' },
  list: { lucide: 'List' },
  'file-pen': { lucide: 'FilePen' },
  'pen-square': { lucide: 'PenSquare' },
  lock: { lucide: 'Lock' },
  'lock-open': { lucide: 'LockOpen' },
  chains: { lucide: 'Link2' },
  finance: { lucide: 'Coins' },
  shares: { lucide: 'TrendingUp' },
  youtube: { lucide: 'Youtube' },
  usage: { lucide: 'Zap' },
  mood: { lucide: 'Heart' },
  news: { lucide: 'Newspaper' },
  play: { lucide: 'Play' },
};

const IconContext = createContext(null);

export function IconProvider({ children }) {
  const iconPack = useSettingsStore((s) => s.iconPack);

  const getIcon = useMemo(() => {
    return (name, props = {}) => {
      const mapping = semanticMap[name];
      if (!mapping) return null;
      const lucideName = mapping.lucide;
      const Icon = LucideIcons[lucideName];
      if (!Icon) return null;
      return <Icon size={18} {...props} />;
    };
  }, [iconPack]);

  return (
    <IconContext.Provider value={getIcon}>
      {children}
    </IconContext.Provider>
  );
}

export function useIcon() {
  return useContext(IconContext);
}

export default IconProvider;
