'use strict';

/**
 * Deterministic Stage-2 emitter: turn an approved template's designed HTML into
 * WordPress PHP template file(s) by swapping data-tb-bind / data-tb-loop markers
 * for the right WP/ACF calls. No LLM — this is the contract that makes the
 * "design once, bind generically" model work.
 */

const VOID_TAGS = new Set(['area', 'base', 'br', 'col', 'embed', 'hr', 'img', 'input', 'link', 'meta', 'param', 'source', 'track', 'wbr']);

function escapeRegExp(value) {
  return String(value).replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

// Locate an element by an attribute value, returning its boundaries (balanced).
function findElementByAttr(html, attr, value) {
  const re = new RegExp(`<([a-zA-Z][\\w-]*)\\b[^>]*\\s${attr}=["']${escapeRegExp(value)}["'][^>]*>`, 'i');
  const m = re.exec(html);
  if (!m) return null;

  const tag = m[1].toLowerCase();
  const openStart = m.index;
  const openEnd = openStart + m[0].length;
  const selfClosed = /\/>\s*$/.test(m[0]) || VOID_TAGS.has(tag);
  if (selfClosed) {
    return { tag, openStart, openEnd, innerStart: openEnd, innerEnd: openEnd, end: openEnd, isVoid: true };
  }

  const lower = html.toLowerCase();
  const openRe = new RegExp(`<${tag}\\b`, 'g');
  const closeTag = `</${tag}>`;
  let depth = 1;
  let i = openEnd;
  while (depth > 0 && i < html.length) {
    openRe.lastIndex = i;
    const nextOpenMatch = openRe.exec(lower);
    const nextOpen = nextOpenMatch ? nextOpenMatch.index : -1;
    const nextClose = lower.indexOf(closeTag, i);
    if (nextClose === -1) return null;
    if (nextOpen !== -1 && nextOpen < nextClose) {
      depth += 1;
      i = nextOpen + tag.length + 1;
    } else {
      depth -= 1;
      i = nextClose + closeTag.length;
      if (depth === 0) {
        return { tag, openStart, openEnd, innerStart: openEnd, innerEnd: nextClose, end: i, isVoid: false };
      }
    }
  }
  return null;
}

function phpForBinding(value) {
  if (value === 'post_title') return { php: '<?php the_title(); ?>', whole: false };
  if (value === 'post_content') return { php: '<?php the_content(); ?>', whole: false };
  if (value === 'post_thumbnail') return { php: "<?php the_post_thumbnail('large'); ?>", whole: 'ifVoid' };
  if (value === 'post_date') return { php: '<?php echo esc_html( get_the_date() ); ?>', whole: false };
  if (value === 'post_author') return { php: '<?php the_author(); ?>', whole: false };
  if (value.startsWith('acf:')) {
    const field = value.slice(4).replace(/[^a-z0-9_]/gi, '');
    if (!field) return null;
    return { php: `<?php echo esc_html( get_field('${field}') ); ?>`, whole: false };
  }
  return null;
}

function applyBinding(html, value) {
  const mapping = phpForBinding(value);
  if (!mapping) return html;
  const el = findElementByAttr(html, 'data-tb-bind', value);
  if (!el) return html;

  const replaceWhole = mapping.whole === true || (mapping.whole === 'ifVoid' && el.isVoid);
  if (replaceWhole || el.isVoid) {
    return html.slice(0, el.openStart) + mapping.php + html.slice(el.end);
  }
  return html.slice(0, el.innerStart) + mapping.php + html.slice(el.innerEnd);
}

function stripBuilderAttributes(html) {
  return String(html || '')
    .replace(/\sdata-tb-bind=["'][^"']*["']/gi, '')
    .replace(/\sdata-tb-loop=["'][^"']*["']/gi, '');
}

function transformBindings(mainHtml) {
  let out = String(mainHtml || '');
  const values = new Set();
  const re = /data-tb-bind=["']([^"']+)["']/gi;
  let m = re.exec(out);
  while (m) {
    values.add(m[1]);
    m = re.exec(out);
  }
  for (const value of values) {
    out = applyBinding(out, value);
  }
  return stripBuilderAttributes(out);
}

function extractMainRegion(html) {
  const el = findElementByAttr(html, 'id', 'tb-template-main');
  if (el && !el.isVoid) return html.slice(el.openStart, el.end);
  const m = String(html || '').match(/<main\b[\s\S]*?<\/main>/i);
  return m ? m[0] : null;
}

function pageTemplate({ slug, label, mainPhp }) {
  return `<?php
/**
 * Template for the "${label}" page (page-${slug}.php).
 * Generated by WP Theme Builder.
 */
if (!defined('ABSPATH')) exit;
get_header();
while (have_posts()) : the_post();
?>
${mainPhp}
<?php
endwhile;
get_footer();
`;
}

function singleTemplate({ label, mainPhp, file }) {
  return `<?php
/**
 * ${file} — "${label}".
 * Generated by WP Theme Builder.
 */
if (!defined('ABSPATH')) exit;
get_header();
while (have_posts()) : the_post();
?>
${mainPhp}
<?php
endwhile;
get_footer();
`;
}

/**
 * Emit the WordPress template file(s) for one approved template.
 * @returns {{ files: Record<string,string>, warnings: string[] }}
 */
function emitTemplateFiles({ html, type, slug, cptSlug, label }) {
  const warnings = [];
  const main = extractMainRegion(html);
  if (!main) {
    return { files: {}, warnings: ['No <main id="tb-template-main"> region found — nothing emitted'] };
  }
  const mainPhp = transformBindings(main);

  if (type === 'page') {
    return { files: { [`page-${slug}.php`]: pageTemplate({ slug, label, mainPhp }) }, warnings };
  }

  // single / cpt share the post-loop wrapper; cpt also needs an archive (added later).
  if (type === 'single') {
    return { files: { 'single.php': singleTemplate({ label, mainPhp, file: 'single.php' }) }, warnings };
  }
  if (type === 'cpt') {
    const cs = cptSlug || slug;
    return {
      files: { [`single-${cs}.php`]: singleTemplate({ label, mainPhp, file: `single-${cs}.php` }) },
      warnings: [...warnings, 'cpt archive + registration not yet emitted (Phase 2)'],
    };
  }

  return { files: {}, warnings: [`Unknown template type: ${type}`] };
}

module.exports = {
  emitTemplateFiles,
  transformBindings,
  extractMainRegion,
  findElementByAttr,
};
