export const DEFAULT_FEATURE_ACCESS = {
  clients: true,
  goals: true,
  habitsSidebar: true,
  memberModelSelection: false,
  chains: true,
  graph: true,
  debate: true,
  compare: true,
  finance: true,
  usage: true,
  mood: true,
  newsDigest: true,
  student: true,
  shares: true,
  youtube: true,
  gmailIntel: true,
};

export const FEATURE_ACCESS_OPTIONS = [
  { key: 'clients', label: 'Clients' },
  { key: 'goals', label: 'Goals' },
  { key: 'habitsSidebar', label: '7 Habits Sidebar' },
  { key: 'memberModelSelection', label: 'Model Selection (Members)' },
  { key: 'chains', label: 'Prompt Chains' },
  { key: 'graph', label: 'Knowledge Graph' },
  { key: 'debate', label: 'Debate' },
  { key: 'compare', label: 'Document Compare' },
  { key: 'finance', label: 'Finance' },
  { key: 'usage', label: 'Usage & Cost' },
  { key: 'mood', label: 'Mood' },
  { key: 'newsDigest', label: 'News Digest' },
  { key: 'student', label: 'Student (Quiz & Cards)' },
  { key: 'shares', label: 'Shares' },
  { key: 'youtube', label: 'YouTube' },
  { key: 'gmailIntel', label: 'Inbox Intel' },
];

