const { createDesignMessage } = require('../utils/modelCall');
const { parseJsonResponse, extractPhp, extractCss } = require('../utils/parseThemeOutput');
const { writeFile, tryReadFile, listFiles } = require('../utils/filewriter');
const { emitTemplateFiles } = require('../utils/templateEmit');
const {
  buildCall1AnalysisPrompt,
  buildCall2StylePrompt,
  buildCall3FunctionsPrompt,
  buildCall4HeaderFooterPrompt,
  buildCall5TemplatesPrompt,
  buildCall6AcfJsonPrompt,
  buildCall7BlocksPrompt,
  buildCall8ReadmePrompt,
} = require('../prompts/stage2-wordpress');

function slugifyTheme(text) {
  return String(text || 'my-theme')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '') || 'my-theme';
}

function themePath(themeSlug, relative = '') {
  return `theme/${themeSlug}${relative ? `/${relative}` : ''}`;
}

async function callModelJson(prompt, ctx, maxTokens = 8000) {
  const { text } = await createDesignMessage({ ...prompt, ...ctx, maxTokens, stage: 'stage2' });
  return parseJsonResponse(text);
}

function fallbackAnalysis(wpData, intakeData) {
  return {
    sections: [],
    editableAreas: [],
    acfFields: wpData?.acfFields?.pages || {},
    repeatingElements: (wpData?.customPostTypes?.types || []).map((type) => ({
      type,
      suggestedCpt: type,
      fields: (wpData?.customPostTypes?.typeFields?.[type] || '').split(',').map((f) => f.trim()).filter(Boolean),
    })),
    blocks: [],
    navMenus: [{ location: 'primary', label: 'Primary Menu' }],
    templateParts: [],
    intakeSummary: intakeData?.purpose || {},
    source: 'fallback',
  };
}

function fallbackStyleCss(themeSlug, wpData, approvedCss) {
  const setup = wpData?.setup || {};
  const header = `/*
Theme Name: ${setup.themeName || themeSlug}
Theme URI:
Author: ${setup.authorName || 'Theme Builder'}
Author URI:
Description: Generated by WP Theme Builder
Version: ${setup.themeVersion || '1.0.0'}
Requires at least: 6.0
Tested up to: 6.7
Requires PHP: 8.0
Text Domain: ${themeSlug}
Requires Plugins: advanced-custom-fields-pro
*/\n\n`;
  return header + (approvedCss || 'body { margin: 0; }');
}

function fallbackFunctionsPhp(themeSlug, wpData, { hasResponsive = false } = {}) {
  const fn = themeSlug.replace(/-/g, '_');
  const cpts = wpData?.customPostTypes?.types || [];
  const cptRegs = cpts.map((type) => {
    const slug = type.toLowerCase().replace(/[^a-z0-9]+/g, '_');
    return `
  register_post_type('${slug}', [
    'labels' => ['name' => '${type}', 'singular_name' => '${type}'],
    'public' => true,
    'has_archive' => true,
    'show_in_rest' => true,
    'supports' => ['title', 'editor', 'thumbnail'],
    'menu_icon' => 'dashicons-admin-post',
  ]);`;
  }).join('\n');

  const optionsPage = wpData?.globalOptions?.enabled
    ? `
  if (function_exists('acf_add_options_page')) {
    acf_add_options_page(['page_title' => 'Theme Options', 'menu_title' => 'Theme Options', 'menu_slug' => '${fn}_options']);
  }`
    : '';

  return `<?php
if (!defined('ABSPATH')) exit;

function ${fn}_setup() {
  add_theme_support('title-tag');
  add_theme_support('post-thumbnails');
  add_theme_support('html5', ['search-form', 'comment-form', 'comment-list', 'gallery', 'caption', 'style', 'script']);
  register_nav_menus(['primary' => __('Primary Menu', '${themeSlug}')]);
}
add_action('after_setup_theme', '${fn}_setup');

function ${fn}_enqueue_assets() {
  wp_enqueue_style('${themeSlug}-style', get_stylesheet_uri(), [], '${setupVersion(wpData)}');
  ${hasResponsive ? `wp_enqueue_style('${themeSlug}-responsive', get_template_directory_uri() . '/responsive.css', ['${themeSlug}-style'], '${setupVersion(wpData)}');` : ''}
}
add_action('wp_enqueue_scripts', '${fn}_enqueue_assets');

function ${fn}_register_cpts() {${cptRegs}
}
add_action('init', '${fn}_register_cpts');
${optionsPage}
`;
}

function setupVersion(wpData) {
  return wpData?.setup?.themeVersion || '1.0.0';
}

function fallbackHeaderFooter(approvedHtml) {
  const headerMatch = approvedHtml.match(/<header[\s\S]*?<\/header>/i);
  const footerMatch = approvedHtml.match(/<footer[\s\S]*?<\/footer>/i);

  const header = `<?php
if (!defined('ABSPATH')) exit;
?><!DOCTYPE html>
<html <?php language_attributes(); ?>>
<head>
  <meta charset="<?php bloginfo('charset'); ?>">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <?php wp_head(); ?>
</head>
<body <?php body_class(); ?>>
${headerMatch ? headerMatch[0] : '<header class="site-header"><div class="site-branding"><?php bloginfo("name"); ?></div></header>'}
`;

  const footer = `<?php
if (!defined('ABSPATH')) exit;
?>
${footerMatch ? footerMatch[0] : '<footer class="site-footer"><p>&copy; <?php echo esc_html(date("Y")); ?> <?php bloginfo("name"); ?></p></footer>'}
<?php wp_footer(); ?>
</body>
</html>
`;

  return { 'header.php': header, 'footer.php': footer };
}

function fallbackTemplates(themeSlug) {
  const fn = themeSlug.replace(/-/g, '_');
  return {
    'front-page.php': `<?php
if (!defined('ABSPATH')) exit;
get_header();
?>
<main id="primary" class="site-main">
  <?php get_template_part('template-parts/home', 'hero'); ?>
</main>
<?php get_footer();`,
    'page.php': `<?php
if (!defined('ABSPATH')) exit;
get_header();
while (have_posts()) : the_post();
?>
<main id="primary" class="site-main">
  <article <?php post_class(); ?>>
    <h1><?php the_title(); ?></h1>
    <div class="entry-content"><?php the_content(); ?></div>
  </article>
</main>
<?php endwhile; get_footer();`,
    'template-parts': {
      'home-hero.php': `<?php
if (!defined('ABSPATH')) exit;
$title = get_field('hero_title') ?: get_bloginfo('name');
?>
<section class="hero">
  <h1><?php echo esc_html($title); ?></h1>
</section>`,
    },
  };
}

function fallbackAcfJson(wpData, themeSlug) {
  const groups = {};
  const pages = wpData?.acfFields?.pages || {};

  Object.entries(pages).forEach(([pageName, fields], index) => {
    const key = `group_${themeSlug}_${index}`;
    groups[`${key}.json`] = {
      key,
      title: `${pageName} Fields`,
      fields: (fields || []).map((field, i) => ({
        key: `field_${key}_${i}`,
        label: field.label,
        name: field.key,
        type: 'text',
      })),
      location: [[{ param: 'page_template', operator: '==', value: 'default' }]],
      active: true,
    };
  });

  return { 'acf-json': groups };
}

function fallbackBlocks() {
  return { blocks: [] };
}

function fallbackReadme(themeSlug, wpData) {
  const setup = wpData?.setup || {};
  return {
    'README.md': `# ${setup.themeName || themeSlug}

## Install
1. Upload the \`${themeSlug}\` folder to \`wp-content/themes/\`
2. Activate the theme in **Appearance → Themes**
3. Install and activate **Advanced Custom Fields PRO**

## ACF field sync
1. Go to **ACF → Field Groups**
2. Use **Sync available** for JSON in \`acf-json/\`

## Required plugins
- Advanced Custom Fields PRO

## Menus
Register a menu under **Appearance → Menus** and assign to **Primary Menu**.

## Fields
Editable content is managed via ACF field groups synced from \`acf-json/\`.
`,
  };
}

async function saveThemeFile(sessionId, themeSlug, relativePath, content) {
  if (content == null) return;
  const body = typeof content === 'object' ? JSON.stringify(content, null, 2) : String(content);
  await writeFile(sessionId, themePath(themeSlug, relativePath), body);
}

async function generateWordPressTheme({
  sessionId,
  intakeData,
  wpData,
  approvedHtml,
  approvedCss,
  approvedResponsiveCss = '',
  ctx,
  onProgress,
}) {
  const themeSlug = slugifyTheme(wpData?.setup?.themeName);
  const progress = (step, detail) => onProgress?.({ step, detail });

  progress(1, 'Analysing HTML');
  let analysis;
  try {
    analysis = await callModelJson(
      buildCall1AnalysisPrompt({ approvedHtml, approvedCss, intakeData, wpData }),
      ctx,
      8000
    );
  } catch {
    analysis = fallbackAnalysis(wpData, intakeData);
  }
  await writeFile(sessionId, 'stage2/analysis.json', JSON.stringify(analysis, null, 2));

  progress(2, 'Generating style.css');
  let styleResult;
  try {
    styleResult = await callModelJson(
      buildCall2StylePrompt({ analysis, wpData, approvedCss, themeSlug }),
      ctx,
      8000
    );
  } catch {
    styleResult = { 'style.css': fallbackStyleCss(themeSlug, wpData, approvedCss) };
  }
  const baseStyleCss = styleResult['style.css'] || fallbackStyleCss(themeSlug, wpData, approvedCss);
  await saveThemeFile(sessionId, themeSlug, 'style.css', baseStyleCss);

  if (approvedResponsiveCss) {
    await saveThemeFile(sessionId, themeSlug, 'responsive.css', approvedResponsiveCss);
  }

  progress(3, 'Generating functions.php');
  let functionsResult;
  try {
    functionsResult = await callModelJson(
      buildCall3FunctionsPrompt({ analysis, wpData, themeSlug }),
      ctx,
      8000
    );
  } catch {
    functionsResult = { 'functions.php': fallbackFunctionsPhp(themeSlug, wpData, { hasResponsive: Boolean(approvedResponsiveCss) }) };
  }
  await saveThemeFile(sessionId, themeSlug, 'functions.php', extractPhp(functionsResult['functions.php'] || fallbackFunctionsPhp(themeSlug, wpData, { hasResponsive: Boolean(approvedResponsiveCss) })));

  progress(4, 'Generating header.php and footer.php');
  let shellResult;
  try {
    shellResult = await callModelJson(
      buildCall4HeaderFooterPrompt({ analysis, approvedHtml, themeSlug }),
      ctx,
      8000
    );
  } catch {
    shellResult = fallbackHeaderFooter(approvedHtml);
  }
  await saveThemeFile(sessionId, themeSlug, 'header.php', extractPhp(shellResult['header.php']));
  await saveThemeFile(sessionId, themeSlug, 'footer.php', extractPhp(shellResult['footer.php']));

  progress(5, 'Generating templates');
  let templatesResult;
  try {
    templatesResult = await callModelJson(
      buildCall5TemplatesPrompt({ analysis, wpData, approvedHtml, themeSlug }),
      ctx,
      12000
    );
  } catch {
    templatesResult = fallbackTemplates(themeSlug);
  }
  await saveThemeFile(sessionId, themeSlug, 'front-page.php', extractPhp(templatesResult['front-page.php']));
  if (templatesResult['page.php']) {
    await saveThemeFile(sessionId, themeSlug, 'page.php', extractPhp(templatesResult['page.php']));
  }
  const parts = templatesResult['template-parts'] || {};
  for (const [name, content] of Object.entries(parts)) {
    await saveThemeFile(sessionId, themeSlug, `template-parts/${name}`, extractPhp(content));
  }

  // Emit deterministic PHP for each approved non-homepage template (page/single/cpt).
  // These swap data-tb-bind / data-tb-loop markers for WP/ACF calls and, by the WP
  // template hierarchy, take precedence over the generic page.php above.
  progress(5, 'Emitting page templates');
  const templateAdditions = [];
  try {
    const metaRaw = await tryReadFile(sessionId, 'meta.json');
    const meta = metaRaw ? JSON.parse(metaRaw) : {};
    const items = (meta.pages?.items || []).filter((i) => i.status === 'approved');
    for (const item of items) {
      const dir = `stage1/templates/${item.slug}`;
      const html = (await tryReadFile(sessionId, `${dir}/approved/index.html`)) || (await tryReadFile(sessionId, `${dir}/index.html`));
      if (!html) continue;
      const { files } = emitTemplateFiles({
        html,
        type: item.template,
        slug: item.slug,
        cptSlug: item.cptSlug || null,
        label: item.label || item.slug,
      });
      for (const [filename, content] of Object.entries(files)) {
        await saveThemeFile(sessionId, themeSlug, filename, content);
      }
      const additions = (await tryReadFile(sessionId, `${dir}/approved/additions.css`)) || (await tryReadFile(sessionId, `${dir}/additions.css`));
      if (additions && additions.trim()) {
        templateAdditions.push(`/* === ${item.label || item.slug} (${item.template}) === */\n${additions.trim()}`);
      }
    }
  } catch {
    // Templates are optional; a malformed meta shouldn't abort theme generation.
  }
  if (templateAdditions.length) {
    const mergedStyle = `${baseStyleCss}\n\n/* === template styles === */\n${templateAdditions.join('\n\n')}\n`;
    await saveThemeFile(sessionId, themeSlug, 'style.css', mergedStyle);
  }

  progress(6, 'Generating ACF JSON');
  let acfResult;
  try {
    acfResult = await callModelJson(
      buildCall6AcfJsonPrompt({ analysis, wpData, themeSlug }),
      ctx,
      12000
    );
  } catch {
    acfResult = fallbackAcfJson(wpData, themeSlug);
  }
  const acfFiles = acfResult['acf-json'] || {};
  for (const [filename, group] of Object.entries(acfFiles)) {
    await saveThemeFile(sessionId, themeSlug, `acf-json/${filename}`, group);
  }

  progress(7, 'Generating block files');
  let blocksResult;
  try {
    blocksResult = await callModelJson(
      buildCall7BlocksPrompt({ analysis, wpData, themeSlug }),
      ctx,
      12000
    );
  } catch {
    blocksResult = fallbackBlocks();
  }
  for (const block of blocksResult.blocks || []) {
    const slug = block.slug || 'block';
    if (block['block.json']) {
      await saveThemeFile(sessionId, themeSlug, `blocks/${slug}/block.json`, block['block.json']);
    }
    if (block['render.php']) {
      await saveThemeFile(sessionId, themeSlug, `blocks/${slug}/render.php`, extractPhp(block['render.php']));
    }
    if (block['style.css']) {
      await saveThemeFile(sessionId, themeSlug, `blocks/${slug}/style.css`, extractCss(block['style.css']));
    }
  }

  progress(8, 'Generating README');
  if (wpData?.setup?.includeReadme !== false) {
    let readmeResult;
    try {
      readmeResult = await callModelJson(
        buildCall8ReadmePrompt({ analysis, wpData, themeSlug }),
        ctx,
        4000
      );
    } catch {
      readmeResult = fallbackReadme(themeSlug, wpData);
    }
    await saveThemeFile(sessionId, themeSlug, 'README.md', readmeResult['README.md'] || fallbackReadme(themeSlug, wpData)['README.md']);
  }

  await saveThemeFile(sessionId, themeSlug, 'index.php', `<?php
// Silence is golden.
`);

  const files = await listFiles(sessionId, themePath(themeSlug));
  return { themeSlug, analysis, files };
}

module.exports = {
  slugifyTheme,
  themePath,
  generateWordPressTheme,
};
